name: Build and smoketest charm

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Create charm package
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2.3.4
      - name: Install lxd
        run: |
          sudo lxd init --auto
          sudo usermod --append --groups lxd $USER
          sg lxd -c 'lxc version'
          sg lxd -c 'lxc network set lxdbr0 ipv6.address none'
      - name: Install charmcraft
        run: sudo snap install charmcraft
      - name: Build charm
        run: |
          set -x
          cp hacks/lxd-profile.yaml .
          charmcraft build
      - name: Uploading snap
        uses: actions/upload-artifact@v2.2.4
        with:
          name: microk8s.charm
          path: microk8s.charm
      - name: Install tox
        run: |
          sudo apt-get install tox
      - name: Run integration tests
        run: |
          set -x
          sudo snap install juju --classic
          sudo snap install juju-wait --classic
          sg lxd -c 'juju bootstrap localhost'
          export MK8S_CLUSTER_SIZE=1
          export MK8S_CHARM=./microk8s.charm
          tox -e integration
