name: Build and smoketest charm

on: [push]
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  build:
    name: Integration tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2.3.4
      - name: Configure pytest-operator
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
      - name: Add user to lxd group
        run: sudo usermod -a -G lxd $USER
      - name: Build charm
        run: |
          set -x
          cp hacks/lxd-profile.yaml .
          sg lxd -c 'charmcraft build'
      - name: Uploading snap
        uses: actions/upload-artifact@v2.2.4
        with:
          name: microk8s.charm
          path: microk8s*.charm
      - name: Install tox
        run: |
          sudo apt-get install tox
      - name: Run integration tests
        run: |
          export MK8S_CLUSTER_SIZE=1
          export MK8S_CHARM=./microk8s.charm
          sg lxd -c 'tox -e integration'
